language: node_js
node_js:
  - 14.15.3
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  # Run linter
  - npm run lint
  # Run build
  - npm run build
branches:
  only:
    - master